insert into marca_veiculo (marveicod, marveinom) values (6,'AUDI');
insert into marca_veiculo (marveicod, marveinom) values (7,'BMW');
insert into marca_veiculo (marveicod, marveinom) values (13,'CITROEN');
insert into marca_veiculo (marveicod, marveinom) values (21,'FIAT');
insert into marca_veiculo (marveicod, marveinom) values (22,'FORD');
insert into marca_veiculo (marveicod, marveinom) values (23,'CHEVROLET');
insert into marca_veiculo (marveicod, marveinom) values (25,'HONDA');
insert into marca_veiculo (marveicod, marveinom) values (26,'HYUNDAI');
insert into marca_veiculo (marveicod, marveinom) values (31,'KIA');
insert into marca_veiculo (marveicod, marveinom) values (39,'MERCEDES-BENZ');
insert into marca_veiculo (marveicod, marveinom) values (41,'MITSUBISHI');
insert into marca_veiculo (marveicod, marveinom) values (43,'NISSAN');
insert into marca_veiculo (marveicod, marveinom) values (44,'PEUGEOT');
insert into marca_veiculo (marveicod, marveinom) values (48,'RENAULT');
insert into marca_veiculo (marveicod, marveinom) values (55,'SUZUKI');
insert into marca_veiculo (marveicod, marveinom) values (56,'TOYOTA');
insert into marca_veiculo (marveicod, marveinom) values (58,'VOLVO');
insert into marca_veiculo (marveicod, marveinom) values (59,'VOLKSWAGEN');
insert into marca_veiculo (marveicod, marveinom) values (1,'ACURA');
insert into marca_veiculo (marveicod, marveinom) values (2,'AGRALE');
insert into marca_veiculo (marveicod, marveinom) values (3,'ALFA ROMEO');
insert into marca_veiculo (marveicod, marveinom) values (4,'AM GEN');
insert into marca_veiculo (marveicod, marveinom) values (5,'ASIA MOTORS');
insert into marca_veiculo (marveicod, marveinom) values (189,'ASTON MARTIN');
insert into marca_veiculo (marveicod, marveinom) values (8,'BRM');
insert into marca_veiculo (marveicod, marveinom) values (9,'UGGY');
insert into marca_veiculo (marveicod, marveinom) values (123,'BUGRE');
insert into marca_veiculo (marveicod, marveinom) values (10,'CADILLAC');
insert into marca_veiculo (marveicod, marveinom) values (11,'CBT JIPE');
insert into marca_veiculo (marveicod, marveinom) values (136,'CHANA');
insert into marca_veiculo (marveicod, marveinom) values (182,'CHANGAN');
insert into marca_veiculo (marveicod, marveinom) values (161,'CHERY');
insert into marca_veiculo (marveicod, marveinom) values (12,'CHRYSLER');
insert into marca_veiculo (marveicod, marveinom) values (14,'CROSS LANDER');
insert into marca_veiculo (marveicod, marveinom) values (15,'DAEWOO');
insert into marca_veiculo (marveicod, marveinom) values (16,'AIHATSU');
insert into marca_veiculo (marveicod, marveinom) values (17,'DODGE');
insert into marca_veiculo (marveicod, marveinom) values (147,'FFA');
insert into marca_veiculo (marveicod, marveinom) values (18,'ENGESA');
insert into marca_veiculo (marveicod, marveinom) values (19,'ENVEMO');
insert into marca_veiculo (marveicod, marveinom) values (20,'FERRARI');
insert into marca_veiculo (marveicod, marveinom) values (149,'FIBRAVAN');
insert into marca_veiculo (marveicod, marveinom) values (190,'FOTON');
insert into marca_veiculo (marveicod, marveinom) values (170,'FYBER');
insert into marca_veiculo (marveicod, marveinom) values (199,'GEELY');
insert into marca_veiculo (marveicod, marveinom) values (153,'GREAT WALL');
insert into marca_veiculo (marveicod, marveinom) values (24,'GURGEL');
insert into marca_veiculo (marveicod, marveinom) values (152,'HAFEI');
insert into marca_veiculo (marveicod, marveinom) values (27,'ISUZU');
insert into marca_veiculo (marveicod, marveinom) values (177,'JAC');
insert into marca_veiculo (marveicod, marveinom) values (28,'JAGUAR');
insert into marca_veiculo (marveicod, marveinom) values (29,'JEEP');
insert into marca_veiculo (marveicod, marveinom) values (154,'JINBEI');
insert into marca_veiculo (marveicod, marveinom) values (30,'JPX');
insert into marca_veiculo (marveicod, marveinom) values (32,'LADA');
insert into marca_veiculo (marveicod, marveinom) values (171,'LAMBORGHINI');
insert into marca_veiculo (marveicod, marveinom) values (33,'LAND ROVER');
insert into marca_veiculo (marveicod, marveinom) values (34,'LEXUS');
insert into marca_veiculo (marveicod, marveinom) values (168,'LIFAN');
insert into marca_veiculo (marveicod, marveinom) values (127,'LOBINI');
insert into marca_veiculo (marveicod, marveinom) values (35,'LOTUS');
insert into marca_veiculo (marveicod, marveinom) values (140,'MAHINDRA');
insert into marca_veiculo (marveicod, marveinom) values (36,'MASERATI');
insert into marca_veiculo (marveicod, marveinom) values (37,'MATRA');
insert into marca_veiculo (marveicod, marveinom) values (38,'MAZDA');
insert into marca_veiculo (marveicod, marveinom) values (40,'MERCURY');
insert into marca_veiculo (marveicod, marveinom) values (167,'MG');
insert into marca_veiculo (marveicod, marveinom) values (156,'MINI');
insert into marca_veiculo (marveicod, marveinom) values (42,'MIURA');
insert into marca_veiculo (marveicod, marveinom) values (45,'PLYMOUTH');
insert into marca_veiculo (marveicod, marveinom) values (46,'PONTIAC');
insert into marca_veiculo (marveicod, marveinom) values (47,'PORSCHE');
insert into marca_veiculo (marveicod, marveinom) values (185,'RAM');
insert into marca_veiculo (marveicod, marveinom) values (186,'RELY');
insert into marca_veiculo (marveicod, marveinom) values (195,'ROLLS-ROYCE');
insert into marca_veiculo (marveicod, marveinom) values (49,'ROVER');
insert into marca_veiculo (marveicod, marveinom) values (50,'SAAB');
insert into marca_veiculo (marveicod, marveinom) values (51,'SATURN');
insert into marca_veiculo (marveicod, marveinom) values (52,'SEAT');
insert into marca_veiculo (marveicod, marveinom) values (183,'SHINERAY');
insert into marca_veiculo (marveicod, marveinom) values (157,'SMART');
insert into marca_veiculo (marveicod, marveinom) values (125,'SSANGYONG');
insert into marca_veiculo (marveicod, marveinom) values (54,'SUBARU');
insert into marca_veiculo (marveicod, marveinom) values (165,'TAC');
insert into marca_veiculo (marveicod, marveinom) values (57,'TROLLER');
insert into marca_veiculo (marveicod, marveinom) values (163,'WAKE');
insert into marca_veiculo (marveicod, marveinom) values (120,'ALK');


